name: Publish to PyPI

on:
  release:
    types:
      - published

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # Used to authenticate to PyPI via OIDC.
      # Used to sign the release's artifacts with sigstore-python.
      id-token: write

      # Used to attach signing artifacts to the published release.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup poetry
        uses: ItsDrike/setup-poetry@v1
        with:
          python-version: 3.11
          install-args: "--only release"

      - name: Set version with dynamic versioning
        run: poetry run poetry-dynamic-versioning

      - name: Build project for distribution
        run: poetry build

      # This uses PyPI's trusted publishing, so no token is required
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Sign distribution files with SignStore and upload back to PyPI
        uses: sigstore/gh-action-sigstore-python@v1.2.3
        with:
          inputs: ./dist/*.tar.gz ./dist/*.whl
          release-signing-artifacts: true
